palette:
  top: '#1b8e05'
  bottom: '#2ab01f'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#057200'
logo: 'public://color/bartik-8b6c08e6/logo.svg'
stylesheets:
  - 'public://color/bartik-8b6c08e6/colors.css'
files:
  - 'public://color/bartik-8b6c08e6/logo.svg'
  - 'public://color/bartik-8b6c08e6/colors.css'
